### ISSUE TITLE
Kanban Board Review

### ISSUE THREAD

**Issue by luigirazum** [luigirazum/book-destinations-api#16]
Dear Code Reviewers, we would like to ask you to review our Kanban Board setup.

- Below is the link to our GitHub project.
https://github.com/luigirazum/book-destinations-api/projects/1

- The team is a 3 member people.
  - @luigirazum - Luis Zubia
  - @vikas924  - Vikas chib
  - @Obimbo07 - Austin Obimbo

- Below you will find the screenshots of our board.
  - Page 1/2
    ![image](https://github.com/luigirazum/book-destinations-api/assets/67355479/26ab1019-9c52-40a0-b4d0-c6049cec1850)

  - Page 2/2
    ![image](https://github.com/luigirazum/book-destinations-api/assets/67355479/2f0e8bb5-00d0-4cc0-98a1-b3ec21b58539)

**Comment by Meltrust** [comment]
## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees, and pointings according to spec✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
